---
- name: Install Cinder
  hosts: all
  become: true

  tasks:
    - name: Install Cinder package
      apt:
        name: cinder-volume
        state: present

    - name: Sync Cinder database
      command: cinder-manage db sync

    - name: Start Cinder services
      systemd:
        name: cinder-volume
        enabled: true
