---
- name: Install Neutron
  hosts: all
  become: true

  tasks:
    - name: Install Neutron pacakge
      apt:
        name: neutron-server
        state: present



    - name: Start Neutron Services
      systemd:
        name: neutron-server
        state: started
        enabled: true
